#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i "/listen 80 default_server;
sed -i '14a \\tadd_header X-Served-By '39055-web-01';' /etc/nginx/nginx.conf
service nginx start
