#!/usr/bin/env bash
# configure a brand new NGINX server
	
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
	
sudo sed -i '14a \\tadd_header X-Served-By '39055-web-01';' /etc/nginx/nginx.conf 

sudo service nginx restart
