#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.html
sudo sed -i '14a \\tadd_header X-Served-By '39055-web-01';' /etc/nginx/nginx.conf
sudo service nginx start
